### ISSUE TITLE
Failed build with create_root_signature is not found on line 73 in D3D12Contents.cpp

### ISSUE THREAD

**Issue by bzindovic** [ZackShrout/HavanaEngine#1]
Hi, my build in Visual Studio 2022 is failing at line 73 with the following message:
`error C3861: 'create_root_signature': identifier not found`
I presume that the problem is that line 73 expects `create_root_signature(info.type, (shader_flags::flags)flags)` with two parameters while I could only find definition of `create_root_signature` with one parameter.

**Comment by ZackShrout** [comment]
Issue resolved
